/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#353534",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "inverse-on-surface": "#313030",
        "on-background": "#e5e2e1",
        "on-secondary-fixed": "#410000",
        "surface-dim": "#131313",
        "outline": "#b18780",
        "primary-container": "#ff5540",
        "surface-variant": "#353534",
        "surface-tint": "#ffb4a8",
        "background": "#131313",
        "on-secondary-fixed-variant": "#930100",
        "on-error-container": "#ffdad6",
        "on-primary": "#690100",
        "on-tertiary": "#621109",
        "secondary-fixed": "#ffdad4",
        "secondary-container": "#970100",
        "on-secondary-container": "#ff9f90",
        "primary": "#ffb4a8",
        "tertiary-fixed": "#ffdad4",
        "on-tertiary-fixed": "#410000",
        "on-tertiary-container": "#580904",
        "surface-container": "#201f1f",
        "on-surface": "#e5e2e1",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#81281d",
        "on-error": "#690005",
        "outline-variant": "#603e39",
        "surface-bright": "#3a3939",
        "tertiary-container": "#e16f5e",
        "surface": "#131313",
        "secondary": "#ffb4a8",
        "on-surface-variant": "#ebbbb4",
        "tertiary": "#ffb4a8",
        "on-primary-container": "#5c0000",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "secondary-fixed-dim": "#ffb4a8",
        "tertiary-fixed-dim": "#ffb4a8",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#690100",
        "inverse-primary": "#c00100",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#930100",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#410000"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
      animation: {
        'star-movement-bottom': 'star-movement-bottom linear infinite alternate',
        'star-movement-top': 'star-movement-top linear infinite alternate',
      },
      keyframes: {
        'star-movement-bottom': {
          '0%': { transform: 'translate(0%, 0%)', opacity: '1' },
          '100%': { transform: 'translate(-100%, 0%)', opacity: '0' },
        },
        'star-movement-top': {
          '0%': { transform: 'translate(0%, 0%)', opacity: '1' },
          '100%': { transform: 'translate(100%, 0%)', opacity: '0' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
