spring.application.name=v_1.0
server.port=8080

# spring.datasource.url=jdbc:postgresql://localhost:5432/makeithook
# spring.datasource.username=postgres
# spring.datasource.password=yourpassword
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connects to your FastAPI server
python.ai.url=http://localhost:8000/api/v1/analyze