spring.application.name=backend
# ── Server ────────────────────────────────────────────────────────────────────
server.port=8080

# ── Database ──────────────────────────────────────────────────────────────────
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/YtAdvisor}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:juniorjain}
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA ───────────────────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ── Flyway ────────────────────────────────────────────────────────────────────
# spring.flyway.enabled=true
# spring.flyway.locations=classpath:db/migration
# spring.jpa.defer-datasource-initialization=true
# # spring.flyway.baseline-on-migrate=true
# # spring.flyway.validate-on-migrate=true
logging.level.org.flywaydb=DEBUG

# ── OAuth2 Google ─────────────────────────────────────────────────────────────
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:179465564896-5u2ght8c940oaidifiqa5etnbt8th86a.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=false
server.address=localhost
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
spring.session.store-type=none

# ── App ───────────────────────────────────────────────────────────────────────
app.jwt-secret=${JWT_SECRET: pqrb3494b903rjrigj024b3nbmdfls394g3gbhvqgi97qhgb3evb0}
app.jwt-expiry-ms=86400000
app.python-base-url=${PYTHON_BASE_URL:http://localhost:8000}
app.frontend-url=${FRONTEND_URL:http://localhost:5173}

# ── YouTube ───────────────────────────────────────────────────────────────────
youtube.api-key=${YOUTUBE_API_KEY:AIzaSyCZyBCWI4W3HWUWs7llNZTawtKFonIDsk4}
